# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uWuJPJhAiql84R63SMaavgBH4oUrYAl

# Data Science Tools and EcosystemEcosystem

In this notebook, Data Science Tools and Ecosystem are summarized.In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL
4. Julia
5. ScalaSome of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL
4. Julia
Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL
4. Julia
5. ScalaScala

Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. NumPy
3. Matplotlib
4. Scikit-learn
5. TensorFlowSome of the commonly used libraries used by Data Scientists include:
1. Pandas
2. NumPy
3. Matplotlib
4. Scikit-learn
Some of the commonly used libraries used by Data Scientists include:
1. Pandas
2. NumPy
3. Matplotlib
4. Scikit-learn
5. TensorFlowTensorFlow

| Data Science Tools |
|--------------------|
| Jupyter Notebook   |
| RStudio            |
| Apache Zeppelin    |

### Below are a few examples of evaluating arithmetic expressions in Python
"""

# This is a simple arithmetic expression to multiply then add integers
(3 * 4) + 5

# This will convert 200 minutes to hours by dividing by 60
200 / 60

"""**Objectives:**
- List popular languages for Data Science
- List commonly used libraries for Data Science
- Create tables in markdown
- Perform arithmetic operations in Python
- Convert units in Python

## Author
Anwar Jafer
"""